/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmac;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anshul
 */
public class Display_Clients extends javax.swing.JInternalFrame {

    /**
     * Creates new form Display_Clients
     */
    public Display_Clients() {
        initComponents();this.setSize(500,500);
        int cname;
       DefaultTableModel dt=new DefaultTableModel();
JTable table=new JTable();
        table.setModel(dt);
table.setEnabled(false);
        String [] columnNames={"S.No","ID No","Client Name","Email Address"};
        dt.setColumnIdentifiers(columnNames);
table.setModel(dt);
 table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
table.setFillsViewportHeight(true);
JScrollPane scroll = new JScrollPane(table);
scroll.setHorizontalScrollBarPolicy(
JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
scroll.setVerticalScrollBarPolicy(
JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);



try
{  String  fname, coname,courrse, pno, email, address,a,b,c;
    Class.forName("com.mysql.jdbc.Driver");//loads driver
      
String url11="jdbc:mysql://localhost/hmac?user=root&password=india@123";
Connection cn; 
        
            cn = DriverManager.getConnection(url11); //connection established
      

String sql = "select * from register";
PreparedStatement ps = cn.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int count=0;
while(rs.next())
{
    
    if(!rs.getString(2).equals("admin@admin")){
    
    count++;

 cname = count;
                    fname = rs.getString(1);
                    pno = rs.getString(4);
                    email= rs.getString(2);
                    
                   
                    dt.addRow(new Object[]{cname, fname,  pno, email});


}
}


      //  table.setBackground(new Color(210,235,245));




        }
catch(Exception e)
{
JOptionPane.showMessageDialog(null, e.getMessage());
}jPanel1.add(scroll);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setMaximizable(true);
        setTitle("Display Clients");
        setToolTipText("Display Clients");
        setMinimumSize(new java.awt.Dimension(300, 300));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Clients Detail");
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
