/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmac;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
 import de.javasoft.plaf.synthetica.SyntheticaAluOxideLookAndFeel;


/**
 *
 * @author Anshul
 */
public class Home extends javax.swing.JFrame implements ActionListener {
JTextField user; JPasswordField Password; JButton  b;JLabel l1;JLabel l2;
public static int session;    


/**
     * Creates new form Home
     */
    public Home() {
        
  
        initComponents();
        this.setResizable(false);
               try {
            // select Look and Feel
 //  UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
            // start application
           UIManager.setLookAndFeel(new SyntheticaAluOxideLookAndFeel());
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
       user =new JTextField();
       this.setTitle("Message Authentication Using Hash Code");
       l1=new JLabel();
       l2=new JLabel();
        Password=new JPasswordField();
        user.setBounds(280, 150, 170, 30);
        jLabel1.add(user);
   
           Password.setBounds(280, 200, 170, 30);
        jLabel1.add(Password);
        l1.setText("Username");
        l1.setForeground(Color.WHITE);
        l2.setText("Password");
           l2.setForeground(Color.WHITE);
        l1.setBounds(200, 150, 170, 30);
       l2.setBounds(200, 200, 170, 30);
      jLabel1.add(l1); jLabel1.add(l2);
      
        b = new JButton("Login");
     //  b.setFont(new Font("Andalus", 3, 14));
       b.setForeground(Color.BLACK);
      
      b.setBounds(300,250,80,30);
b.addActionListener(this);
jLabel1.add(b);
 this.getRootPane().setDefaultButton(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hmac/cover/Technology-Wallpapers-6_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
 String str;   
 
 if(user.getText().trim().length()==0||Password.getPassword().length==0){
 JOptionPane.showMessageDialog(null, "Field Can't be left blank");}else
 {
        str = new String(Password.getPassword());
        
        

        {    
        
        try
{  
    Class.forName("com.mysql.jdbc.Driver");//loads driver
      
String url11="jdbc:mysql://localhost/hmac?user=root&password=india@123";
Connection cn; 
        
            cn = DriverManager.getConnection(url11); //connection established
      

String sql = "select * from register where email='"+user.getText()+"' and pass='"+str+"'";
PreparedStatement ps = cn.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int count=0;
while(rs.next())
{  session=rs.getInt(1);
count++;


      if(rs.getString(2).equals("admin@admin"))
            {
          Admin h=new Admin();
   
    h.setVisible(true);
    }
      
      else {
 Sender_Receiver h=new Sender_Receiver();
   
    h.setVisible(true);
     
                    
      }
      

        }
  
      if(count==0){
        JOptionPane.showMessageDialog(null,"Invalid Credentials");
      
      
      } else {
      
      
      this.setVisible(false);}

 }
      catch(Exception e12)
{
JOptionPane.showMessageDialog(null, e12.getMessage());
}
    
        
        
        
        
        
        
         
           
           
        }

 }}}

