/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmac;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anshul
 */
public class Logs extends javax.swing.JInternalFrame {

    /**
     * Creates new form Display_Doctors
     */
    public Logs() {
        initComponents();
        
        
         DefaultComboBoxModel dm=new DefaultComboBoxModel();
             
 

            String  name,message, status="";
            DefaultTableModel dt = new DefaultTableModel();
             JTable table = new JTable();

          String [] columnNames = {"S.No", "Client Name",  "Message","Status"};
table.setEnabled(false);
            dt.setColumnIdentifiers(columnNames);
           table.setModel(dt); table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
table.setFillsViewportHeight(true);
JScrollPane scroll = new JScrollPane(table);
scroll.setHorizontalScrollBarPolicy(
JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
scroll.setVerticalScrollBarPolicy(
JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
         try {
 Class.forName("com.mysql.jdbc.Driver");//loads driver
      
String url1="jdbc:mysql://localhost/hmac?user=root&password=india@123";
Connection cn; 
        int count=0,id=0;
            cn = DriverManager.getConnection(url1); //connection established
                String sql = "select * from logs where sid='"+Home.session+"' or rid='"+Home.session+"'" ;
                PreparedStatement ps = cn.prepareStatement(sql);
               ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                  
                
                     count++;
                     if(rs.getInt(2)==Home.session)
                     {
                     
                     id=rs.getInt(3);
                      status="Sent";
                     
                     } else  if(rs.getInt(3)==Home.session) {
                       id=rs.getInt(2);
                     status="Received";
                     
                     
                     }
                     retu_class cla=new retu_class();
                     String [] sl=cla.name_email(id).split("-");
                     
                    name = sl[0];                  
                 
                    message= rs.getString(4);
                
                   
                   
                    dt.addRow(new Object[]{count, name,message ,status});
                }
       } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }jPanel2.add(scroll);
        



        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Logs");
        setToolTipText("Logs");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Logs");
        jPanel4.add(jLabel1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jComboBox1.setFont(new java.awt.Font("Arno Pro Caption", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Sent", "Received" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.lightGray), "Display Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 1, 15))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        jPanel2.removeAll();
       
            String  name,message, status="";
            DefaultTableModel dt = new DefaultTableModel();
             JTable table = new JTable();

          String [] columnNames = {"S.No", "Client Name",  "Message","Status"};
table.setEnabled(false);
            dt.setColumnIdentifiers(columnNames);
           table.setModel(dt); table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
table.setFillsViewportHeight(true);
JScrollPane scroll = new JScrollPane(table);
scroll.setHorizontalScrollBarPolicy(
JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
scroll.setVerticalScrollBarPolicy(
JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);  
  int count=0,id=0;
        if (jComboBox1.getSelectedItem().equals("All"))
        {
              DefaultComboBoxModel dm=new DefaultComboBoxModel();
            

         try {
 Class.forName("com.mysql.jdbc.Driver");//loads driver
      
String url1="jdbc:mysql://localhost/hmac?user=root&password=india@123";
Connection cn; 
      
            cn = DriverManager.getConnection(url1); //connection established
                String sql = "select * from logs where sid='"+Home.session+"' or rid='"+Home.session+"'" ;
                PreparedStatement ps = cn.prepareStatement(sql);
               ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                  
                
                     count++;
                     if(rs.getInt(2)==Home.session)
                     {
                     
                     id=rs.getInt(3);
                      status="Sent";
                     
                     } else  if(rs.getInt(3)==Home.session) {
                       id=rs.getInt(2);
                     status="Received";
                     
                     
                     }
                     retu_class cla=new retu_class();
                     String [] sl=cla.name_email(id).split("-");
                     
                    name = sl[0];                  
                  
                    message= rs.getString(4);
                
                   
                   
                    dt.addRow(new Object[]{count, name,message ,status});
                }
       } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }jPanel2.add(scroll);
        
        }

        else {

            try {
                Class.forName("com.mysql.jdbc.Driver");//loads driver

                String url11="jdbc:mysql://localhost/hmac?user=root&password=india@123";
                Connection cn1;

                cn1 = DriverManager.getConnection(url11); //connection established

                String sql = "";
                if(jComboBox1.getSelectedItem().toString().equals("Sent")){
                sql= "select * from logs where sid='"+Home.session+"' " ;
                status="Sent";
                
                
                } else if (jComboBox1.getSelectedItem().toString().equals("Received")){
                sql= "select * from logs where rid='"+Home.session+"' " ;
                status="Received";
                }
                
                PreparedStatement ps = cn1.prepareStatement(sql);
               ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                  
                     if(jComboBox1.getSelectedItem().toString().equals("Sent")){
                     
                     id=rs.getInt(3);
                     
                     }else if (jComboBox1.getSelectedItem().toString().equals("Received")){
                     
                     
                      id=rs.getInt(2);
                     
                     }
                    count++;
                    retu_class cla=new retu_class();
                     String [] sl=cla.name_email(id).split("-");
                     
                    name = sl[0];                  
               
                    message= rs.getString(4);
                
                   
                   
                    dt.addRow(new Object[]{count, name,message ,status});
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }   jPanel2.add(scroll);
        }
        jPanel2.validate();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
